services:
  - type: web
    name: cfo-buddy
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: GOOGLE_API_KEY
        sync: false 